# Use root/example as user/password credentials 
version: '3.1' 

services:

  dc102:
    container_name: dc102
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      
  dc102-adminer:
    container_name: dc102-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  JUPYTERdb: 
    container_name: jupyter-book
    image: jupyter/base-notebook
    restart: always
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - 8888:8888

